# Generated by Django 5.1 on 2025-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0002_booking_end_time_booking_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
