# Generated by Django 5.1 on 2025-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_station_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregister',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
