# Generated by Django 5.1 on 2025-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0004_bike_is_removed_userregister_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
