# Generated by Django 5.1 on 2025-02-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0006_payment_delete_payment_last'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payment_last',
        ),
    ]
