# Generated by Django 5.1.6 on 2025-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0008_remove_booking_date_remove_booking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
