# Generated by Django 5.1 on 2025-03-28 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0009_bike_is_available_alter_bike_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_last',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
