# Generated by Django 5.1 on 2025-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0011_holiday_booking_distance_booking_estimated_demand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
