# Generated by Django 5.1 on 2025-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0012_alter_station_latitude_alter_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.TextField(default='Unknown Location'),
        ),
    ]
