# Generated by Django 5.1 on 2025-03-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0013_station_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
