# Generated by Django 5.1 on 2025-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0014_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bikenum',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
