# Generated by Django 5.1 on 2025-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0015_alter_bike_bikenum_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bikenum',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
