# Generated by Django 5.1.7 on 2025-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0017_booking_penalty_amount_booking_penalty_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
