# Generated by Django 5.1.7 on 2025-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0018_alter_bike_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=100),
        ),
    ]
